site_name: Neureca Wiki
theme: 
  name: material

nav:
  - Home: "index.md"
  - Resources: 
    - Training: "training.md"
  - Standard Operating Procedures :
    - Nameing Conventions : "naming_conventions.md"
    - Data Management: "data_management.md"
  - Extras:
    - Support: "support.md"
    - Tips : "tips.md"
